name: Update docs

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    paths:
      - data/servers/list.json

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: |
          pnpm install
          pnpm update:docs
          pnpm format
          if [ -n "$(git status --porcelain)" ]; then
            echo "skip_commit=false" >> $GITHUB_ENV
          else
            echo "skip_commit=true" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.skip_commit == 'false'
        run: |
          git config --global user.email "luz.liting@gmail.com"
          git config --global user.name "litingyes"
          git add .
          git commit -m "chore(ci): update docs"
          git pull origin main -r
          git push origin main

      - name: Trigger deploy to website
        if: env.skip_commit == 'false'
        run: |
          pnpm add -D netlify-cli
          netlify deploy \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} \
            --prod
